~~~{"variant":"standard","title":"GitHub Actions CI/CD for Journey App","id":"39215"}
name: Journey App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub (fixed)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build backend image
      - name: Build backend image
        run: docker build -t abhilasha360/journey-backend:latest ./backend

      # 4️⃣ Build frontend image
      - name: Build frontend image
        run: docker build -t abhilasha360/journey-frontend:latest ./frontend

      # 5️⃣ Push backend image
      - name: Push backend image
        run: docker push abhilasha360/journey-backend:latest

      # 6️⃣ Push frontend image
      - name: Push frontend image
        run: docker push abhilasha360/journey-frontend:latest

      # 7️⃣ Optional: Deploy to server via SSH
      # Requires server IP, user, and private SSH key as GitHub secrets
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            docker-compose down
            docker-compose pull
            docker-compose up -d
~~~
