~~~{"variant":"standard","title":"Journey App Full CI/CD with SSH","id":"39221"}
name: Journey App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker Hub login
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build backend Docker image
      - name: Build backend image
        run: docker build -t abhilasha360/journey-backend:latest ./backend

      # 4️⃣ Build frontend Docker image
      - name: Build frontend image
        run: docker build -t abhilasha360/journey-frontend:latest ./frontend

      # 5️⃣ Push backend Docker image
      - name: Push backend image
        run: docker push abhilasha360/journey-backend:latest

      # 6️⃣ Push frontend Docker image
      - name: Push frontend image
        run: docker push abhilasha360/journey-frontend:latest

      # 7️⃣ Test SSH connectivity (optional but recommended)
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: echo "SSH connection successful!"
          debug: true

      # 8️⃣ Deploy to server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}          # Your server IP
          username: ${{ secrets.SERVER_USER }}    # SSH user
          key: ${{ secrets.SERVER_SSH_KEY }}      # Private key content from GitHub Secrets
          port: 22
          script: |
            cd /home/ubuntu/journey-app          # Replace with your deployment folder
            docker-compose down
            docker-compose pull
            docker-compose up -d
          debug: true
          timeout: 30s
          command_timeout: 10m
~~~
